### ISSUE TITLE
User settings tests

### ISSUE THREAD

**Issue by corajr** [mooreniemi/Transbucket_Rails#26]
- Turning off notifications
   - [x] prevent emails from being sent
- Clicking submit on user settings
   - [x] updates them on the backend
   - [x] doesn't delete user (re: issue #23)
- Cancellation
   - [x] confirms before deleting, if JS
   - [x] deletes immediately without JS

**Comment by mooreniemi** [comment]
maybe should merge with https://github.com/mooreniemi/Transbucket_Rails/issues/8

**Comment by corajr** [comment]
Some behavior might change (esp.: should password be required to change *any* profile item?), but the tests are in place.
