### ISSUE TITLE
search results page displays wrong

### ISSUE THREAD

**Issue by mooreniemi** [mooreniemi/Transbucket_Rails#69]
I haven't been able to reproduce this locally yet. I think it may be due to comments? But the experience really sucks.

http://www.transbucket.com/pins?utf8=%E2%9C%93&query=glansplasty&commit=Go

![Screenshot from 2021-02-15 17-38-12](https://user-images.githubusercontent.com/1695630/107999085-9afcfe80-6fb4-11eb-80f2-6dc1fb394a51.png)

**Comment by corajr** [comment]
I found some pins on the live site that exhibit this behavior, but can't tell exactly why it's happening.

We might want to consider moving to flexbox and generally making the UI responsive, though that could easily be spun into its own ticket. Fortunately that has gotten much easier to do in recent years.

**Comment by mooreniemi** [comment]
When I look at it, I wonder if it's actually a deeper problem with however the underlying Ruby template or response is formed.

In this case: http://www.transbucket.com/pins?utf8=%E2%9C%93&query=glansoplasty&commit=Go

There's 2 items, but one of them is getting nested in a weird panel, while the other is not.
![Uploading Screenshot from 2021-02-15 21-55-40.png…]()

**Comment by mooreniemi** [comment]
You can see here the nesting:

![search](https://user-images.githubusercontent.com/1695630/108157429-af262600-70b0-11eb-9577-dd27a7440861.png)

**Comment by mooreniemi** [comment]
I think the issue is pre-Masonry, and something in how the actual pins are formed.

**Comment by mooreniemi** [comment]
Ok I think I figured it out. The erb template is nested wrong such that unpublished pins will break the flow. I have a local branch I'll push up for PR and then should be set for deploy.
