### ISSUE TITLE
normalize procedure names

### ISSUE THREAD

**Issue by mooreniemi** [mooreniemi/Transbucket_Rails#76]
Procedures probably should be formed more loosely through clustering, in a tagging type style. But for now it makes sense to at least normalize procedure names so we have fewer duplicates.

- Casing matters. We should store lowercase and display capitalized.
- We should encourage reuse of existing procedure names.
- We should discourage long procedure names (likely to be a laundry list of everything that was done). This gets at the need to allow a Pin to be one to many with procedure, ultimately.

**Comment by mooreniemi** [comment]
First off, I am rendering the procedure names in alphabetical order so that it's easier to see the problem and identify duplicates. I'm hand normalizing some of these as I go. There's maybe a dozen to normalize ultimately. The highest priority is fixing those that just differ due to case.

**Comment by brrusselburg** [comment]
I'm gonna mock up this csv and link it here, if that works
